; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S %s | FileCheck %s

%"struct.archgenlib::FixedNumber" = type { i10 }
%"struct.archgenlib::FixedNumber.0" = type { i4 }

; Function Attrs: mustprogress noinline optnone uwtable
define dso_local void @_Z4testN10archgenlib11FixedNumberINS_11FixedFormatILi4ELin5EiEEEE(i16 %x.coerce) #0 {
; CHECK-LABEL: @_Z4testN10archgenlib11FixedNumberINS_11FixedFormatILi4ELin5EiEEEE(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X:%.*]] = alloca %"struct.archgenlib::FixedNumber", align 2
; CHECK-NEXT:    [[OUT:%.*]] = alloca %"struct.archgenlib::FixedNumber.0", align 1
; CHECK-NEXT:    [[COERCE_DIVE:%.*]] = getelementptr inbounds %"struct.archgenlib::FixedNumber", %"struct.archgenlib::FixedNumber"* [[X]], i32 0, i32 0
; CHECK-NEXT:    [[COERCE_VAL_II:%.*]] = trunc i16 [[X_COERCE:%.*]] to i10
; CHECK-NEXT:    store i10 [[COERCE_VAL_II]], i10* [[COERCE_DIVE]], align 2
; CHECK-NEXT:    call void @_ZN10archgenlib6detail12evaluateImplINS_11FixedNumberINS_11FixedFormatILi2ELin1EjEEEELi0ENS_5AddOpINS_5SinOpINS_8VariableINS2_INS3_ILi4ELin5EiEEEELm0EEEEENS_4PiOpEEEJSA_EEEvRT_DpRT2_(%"struct.archgenlib::FixedNumber.0"* noundef nonnull align 1 dereferenceable(1) [[OUT]], %"struct.archgenlib::FixedNumber"* noundef nonnull align 2 dereferenceable(2) [[X]])
; CHECK-NEXT:    ret void
;
entry:
  %x = alloca %"struct.archgenlib::FixedNumber", align 2
  %out = alloca %"struct.archgenlib::FixedNumber.0", align 1
  %coerce.dive = getelementptr inbounds %"struct.archgenlib::FixedNumber", %"struct.archgenlib::FixedNumber"* %x, i32 0, i32 0
  %coerce.val.ii = trunc i16 %x.coerce to i10
  store i10 %coerce.val.ii, i10* %coerce.dive, align 2
  call void @_ZN10archgenlib6detail12evaluateImplINS_11FixedNumberINS_11FixedFormatILi2ELin1EjEEEELi0ENS_5AddOpINS_5SinOpINS_8VariableINS2_INS3_ILi4ELin5EiEEEELm0EEEEENS_4PiOpEEEJSA_EEEvRT_DpRT2_(%"struct.archgenlib::FixedNumber.0"* noundef nonnull align 1 dereferenceable(1) %out, %"struct.archgenlib::FixedNumber"* noundef nonnull align 2 dereferenceable(2) %x)
  ret void
}

declare dso_local void @_ZN10archgenlib6detail12evaluateImplINS_11FixedNumberINS_11FixedFormatILi2ELin1EjEEEELi0ENS_5AddOpINS_5SinOpINS_8VariableINS2_INS3_ILi4ELin5EiEEEELm0EEEEENS_4PiOpEEEJSA_EEEvRT_DpRT2_(%"struct.archgenlib::FixedNumber.0"* noundef nonnull align 1 dereferenceable(1), %"struct.archgenlib::FixedNumber"* noundef nonnull align 2 dereferenceable(2)) #1

; Function Attrs: mustprogress noinline optnone uwtable
define dso_local void @_Z5test2N10archgenlib11FixedNumberINS_11FixedFormatILi4ELin5EiEEEE(i16 %x.coerce) #0 {
; CHECK-LABEL: @_Z5test2N10archgenlib11FixedNumberINS_11FixedFormatILi4ELin5EiEEEE(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[X:%.*]] = alloca %"struct.archgenlib::FixedNumber", align 2
; CHECK-NEXT:    [[OUT:%.*]] = alloca %"struct.archgenlib::FixedNumber.0", align 1
; CHECK-NEXT:    [[COERCE_DIVE:%.*]] = getelementptr inbounds %"struct.archgenlib::FixedNumber", %"struct.archgenlib::FixedNumber"* [[X]], i32 0, i32 0
; CHECK-NEXT:    [[COERCE_VAL_II:%.*]] = trunc i16 [[X_COERCE:%.*]] to i10
; CHECK-NEXT:    store i10 [[COERCE_VAL_II]], i10* [[COERCE_DIVE]], align 2
; CHECK-NEXT:    call void @_ZN10archgenlib6detail12evaluateImplINS_11FixedNumberINS_11FixedFormatILi2ELin1EjEEEELi0ENS_5AddOpINS_5SinOpINS_8VariableINS2_INS3_ILi4ELin5EiEEEELm0EEEEESC_EEJSA_EEEvRT_DpRT2_(%"struct.archgenlib::FixedNumber.0"* noundef nonnull align 1 dereferenceable(1) [[OUT]], %"struct.archgenlib::FixedNumber"* noundef nonnull align 2 dereferenceable(2) [[X]])
; CHECK-NEXT:    ret void
;
entry:
  %x = alloca %"struct.archgenlib::FixedNumber", align 2
  %out = alloca %"struct.archgenlib::FixedNumber.0", align 1
  %coerce.dive = getelementptr inbounds %"struct.archgenlib::FixedNumber", %"struct.archgenlib::FixedNumber"* %x, i32 0, i32 0
  %coerce.val.ii = trunc i16 %x.coerce to i10
  store i10 %coerce.val.ii, i10* %coerce.dive, align 2
  call void @_ZN10archgenlib6detail12evaluateImplINS_11FixedNumberINS_11FixedFormatILi2ELin1EjEEEELi0ENS_5AddOpINS_5SinOpINS_8VariableINS2_INS3_ILi4ELin5EiEEEELm0EEEEESC_EEJSA_EEEvRT_DpRT2_(%"struct.archgenlib::FixedNumber.0"* noundef nonnull align 1 dereferenceable(1) %out, %"struct.archgenlib::FixedNumber"* noundef nonnull align 2 dereferenceable(2) %x)
  ret void
}

declare dso_local void @_ZN10archgenlib6detail12evaluateImplINS_11FixedNumberINS_11FixedFormatILi2ELin1EjEEEELi0ENS_5AddOpINS_5SinOpINS_8VariableINS2_INS3_ILi4ELin5EiEEEELm0EEEEESC_EEJSA_EEEvRT_DpRT2_(%"struct.archgenlib::FixedNumber.0"* noundef nonnull align 1 dereferenceable(1), %"struct.archgenlib::FixedNumber"* noundef nonnull align 2 dereferenceable(2)) #1

; Function Attrs: mustprogress noinline norecurse nounwind optnone uwtable
define dso_local noundef i32 @main() #2 {
; CHECK-LABEL: @main(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    ret i32 0
;
entry:
  ret i32 0
}

attributes #0 = { mustprogress noinline optnone uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { "frame-pointer"="all" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #2 = { mustprogress noinline norecurse nounwind optnone uwtable "frame-pointer"="all" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
